name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to WP.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_REPOSITORY_URL: ${{ secrets.SVN_Repository_URL }}
          SVN_USER_NAME: ${{ secrets.SVN_USERNAME }}
          SVN_USER_PASSWORD: ${{ secrets.SVN_PASSWORD }}